

services:
  db:
    image: mysql:8.0
    container_name: fourinarow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: four_in_a_row
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: fourinarow_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: four_in_a_row
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: fourinarow_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
